import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateRefreshTokenTable1771428706440 implements MigrationInterface {
    name = 'CreateRefreshTokenTable1771428706440'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "spp" DROP CONSTRAINT "FK_db681b51017ba5bd0294590b22d"`);
        await queryRunner.query(`ALTER TABLE "spp" DROP CONSTRAINT "FK_spp_payment_voucher"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP CONSTRAINT "FK_pva_voucher"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP CONSTRAINT "FK_pval_voucher"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP CONSTRAINT "FK_pval_user"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP CONSTRAINT "FK_d6e99eb250ce00c6734bbfc5f9b"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP CONSTRAINT "FK_pv_tax_rule"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP CONSTRAINT "FK_pv_spp"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tax_rules_pattern"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tax_rules_active"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db681b51017ba5bd0294590b22"`);
        await queryRunner.query(`DROP INDEX "public"."idx_short_urls_hash"`);
        await queryRunner.query(`DROP INDEX "public"."idx_short_urls_target"`);
        await queryRunner.query(`DROP INDEX "public"."idx_short_urls_expires"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pva_voucher"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pva_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pval_voucher"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pval_performed"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pval_action"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pval_performed_by"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pval_metadata"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9be2dca70f1c1dd5b0aabc484b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_249b705de6a6a36f61236f17e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6e99eb250ce00c6734bbfc5f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52e465f91e3cf7db58200dfc7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_79c0ae56db7c4d1c9cc8d52383"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b14c90323ff9527cf9c4d2dbe"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pv_voucher_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pv_fiscal_year"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pv_year_month"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pv_account_code"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pv_kegiatan"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pv_sub_kegiatan"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pv_pptk"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pv_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pv_vendor"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pv_voucher_date"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pv_not_deleted"`);
        await queryRunner.query(`DROP INDEX "public"."idx_pv_sequence_unique"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP CONSTRAINT "chk_gross_amount_positive"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP CONSTRAINT "chk_net_payment_positive"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP CONSTRAINT "chk_deductions_not_exceed_gross"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP CONSTRAINT "chk_spp_only_when_approved"`);
        await queryRunner.query(`ALTER TABLE "spp" RENAME COLUMN "payment_voucher_id" TO "buktiBayarId"`);
        await queryRunner.query(`COMMENT ON TABLE "short_urls" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "payment_voucher_attachments" IS NULL`);
        await queryRunner.query(`COMMENT ON TABLE "payment_voucher_audit_logs" IS NULL`);
        await queryRunner.query(`CREATE TABLE "bukti_bayar" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nomorBuktiBayar" character varying(100) NOT NULL, "tanggalBuktiBayar" TIMESTAMP NOT NULL, "tahunAnggaran" integer NOT NULL, "bulan" integer NOT NULL, "anggaranKasId" uuid NOT NULL, "nilaiPembayaran" numeric(15,2) NOT NULL, "uraian" text NOT NULL, "keterangan" text, "jenisBelanja" "public"."bukti_bayar_jenisbelanja_enum" NOT NULL, "namaPenerima" character varying(255) NOT NULL, "npwpPenerima" character varying(100), "alamatPenerima" character varying(255), "bankPenerima" character varying(255), "rekeningPenerima" character varying(100), "atasNamaRekening" character varying(255), "status" "public"."bukti_bayar_status_enum" NOT NULL DEFAULT 'DRAFT', "submittedBy" uuid, "submittedAt" TIMESTAMP, "verifiedBy" uuid, "verifiedAt" TIMESTAMP, "approvedBy" uuid, "approvedAt" TIMESTAMP, "rejectedBy" uuid, "rejectedAt" TIMESTAMP, "alasanReject" text, "fileLampiran" character varying(500), "fileBuktiBayar" character varying(500), "createdBy" character varying(255) NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_52e465f91e3cf7db58200dfc7cd" UNIQUE ("nomorBuktiBayar"), CONSTRAINT "PK_df4729dbb3a254764e868388949" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_52e465f91e3cf7db58200dfc7c" ON "bukti_bayar" ("nomorBuktiBayar") `);
        await queryRunner.query(`CREATE INDEX "IDX_79c0ae56db7c4d1c9cc8d52383" ON "bukti_bayar" ("tanggalBuktiBayar") `);
        await queryRunner.query(`CREATE INDEX "IDX_9be2dca70f1c1dd5b0aabc484b" ON "bukti_bayar" ("tahunAnggaran") `);
        await queryRunner.query(`CREATE INDEX "IDX_249b705de6a6a36f61236f17e9" ON "bukti_bayar" ("bulan") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6e99eb250ce00c6734bbfc5f9" ON "bukti_bayar" ("anggaranKasId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9fd380654c45b0b207ec89b85d" ON "bukti_bayar" ("jenisBelanja") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b14c90323ff9527cf9c4d2dbe" ON "bukti_bayar" ("status") `);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "ppn_rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pph21_rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pph22_rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pph23_rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pph4a2_rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pph_final_umkm_rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pph24_rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "includes_pbjt"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pbjt_rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "is_final_tax"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "effective_from"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "effective_to"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "account_code_pattern"`);
        await queryRunner.query(`ALTER TABLE "short_urls" DROP COLUMN "target_id"`);
        await queryRunner.query(`ALTER TABLE "short_urls" DROP COLUMN "expires_at"`);
        await queryRunner.query(`ALTER TABLE "short_urls" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "short_urls" DROP COLUMN "target_type"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "voucher_id"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "file_size"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "uploaded_by"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "uploaded_at"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "file_name"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "file_type"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "file_path"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "attachment_type"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP COLUMN "performed_at"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP COLUMN "voucher_id"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP COLUMN "performed_by"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP COLUMN "old_status"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP COLUMN "new_status"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "voucher_date"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "fiscal_year"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "voucher_month"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "rak_id_legacy"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "gross_amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "rejection_by"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "rejected_at"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "voucher_sequence"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "program_id"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "kegiatan_id"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "sub_kegiatan_id"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "available_pagu"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "rak_monthly_limit"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "previous_commitments"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pptk_id"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "invoice_date"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "tax_rule_id"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph21_rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph21_amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph22_rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph22_amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph23_rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph23_amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph4a2_rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph4a2_amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph_final_umkm_rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph_final_umkm_amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph24_rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph24_amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "ppn_rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "ppn_amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "other_deductions"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "includes_pbjt"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pbjt_rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pbjt_amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "sk_umkm_expiry"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "total_deductions"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","total_deductions","sikancil_dev","public","payment_vouchers"]);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "net_payment"`);
        await queryRunner.query(`DELETE FROM "typeorm_metadata" WHERE "type" = $1 AND "name" = $2 AND "database" = $3 AND "schema" = $4 AND "table" = $5`, ["GENERATED_COLUMN","net_payment","sikancil_dev","public","payment_vouchers"]);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "technical_officer_id"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "technical_signed_at"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "receiver_id"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "receiver_signed_at"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "treasurer_id"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "treasurer_signed_at"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "approver_id"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "approver_signed_at"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "spp_id"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "spp_created_at"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "updated_by"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "deleted_by"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP CONSTRAINT "UQ_52e465f91e3cf7db58200dfc7cd"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "voucher_number"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "payment_purpose"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "payee_name"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "rejection_reason"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "unit_code"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "program_code"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "program_name"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "kegiatan_code"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "kegiatan_name"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "sub_kegiatan_code"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "sub_kegiatan_name"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "account_code"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "account_name"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "vendor_name"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "vendor_npwp"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "vendor_address"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "invoice_numbers"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "other_deductions_note"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "sk_umkm_number"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "gross_amount_text"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "technical_officer_name"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "technical_officer_nip"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "technical_notes"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "receiver_name"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "receiver_nip"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "treasurer_name"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "treasurer_nip"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "treasurer_notes"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "approver_name"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "approver_nip"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "accountCodePattern" character varying(60) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "ppnRate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pph21Rate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pph22Rate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pph23Rate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pph4a2Rate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pphFinalUmkmRate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pph24Rate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "includesPbjt" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pbjtRate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "isFinalTax" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "effectiveFrom" date NOT NULL DEFAULT ('now'::text)::date`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "effectiveTo" date`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "createdBy" uuid`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "short_urls" ADD "targetId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "short_urls" ADD "targetType" character varying(50) NOT NULL DEFAULT 'PAYMENT_VOUCHER'`);
        await queryRunner.query(`ALTER TABLE "short_urls" ADD "expiresAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "short_urls" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "voucherId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "fileName" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "fileType" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "fileSize" integer`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "filePath" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "attachmentType" character varying(30) NOT NULL DEFAULT 'OTHER'`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "uploadedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "uploadedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD "voucherId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD "oldStatus" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD "newStatus" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD "performedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD "performedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "voucherNumber" character varying(120) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD CONSTRAINT "UQ_00ab11781bc2d1e83625b78c820" UNIQUE ("voucherNumber")`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "voucherSequence" integer`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "fiscalYear" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "voucherMonth" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "voucherDate" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "unitCode" character varying(20) NOT NULL DEFAULT 'RSUD-DS'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "programId" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "programCode" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "programName" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "kegiatanId" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "kegiatanCode" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "kegiatanName" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "subKegiatanId" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "subKegiatanCode" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "subKegiatanName" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "accountCode" character varying(60)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "accountName" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "availablePagu" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "rakMonthlyLimit" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "previousCommitments" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pptkId" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "payeeName" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "paymentPurpose" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "vendorName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "vendorNpwp" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "vendorAddress" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "invoiceNumbers" text array`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "invoiceDate" date`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "grossAmount" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "taxRuleId" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph21Rate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph21Amount" numeric(15,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph22Rate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph22Amount" numeric(15,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph23Rate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph23Amount" numeric(15,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph4a2Rate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph4a2Amount" numeric(15,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pphFinalUmkmRate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pphFinalUmkmAmount" numeric(15,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph24Rate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph24Amount" numeric(15,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "ppnRate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "ppnAmount" numeric(15,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "otherDeductions" numeric(15,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "otherDeductionsNote" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "includesPbjt" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pbjtRate" numeric(5,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pbjtAmount" numeric(15,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "skUmkmNumber" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "skUmkmExpiry" date`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "totalDeductions" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "netPayment" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "grossAmountText" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "technicalOfficerId" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "technicalOfficerName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "technicalOfficerNip" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "technicalSignedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "technicalNotes" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "receiverId" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "receiverName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "receiverNip" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "receiverSignedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "treasurerId" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "treasurerName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "treasurerNip" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "treasurerSignedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "treasurerNotes" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "approverId" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "approverName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "approverNip" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "approverSignedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "rejectionReason" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "rejectionBy" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "rejectedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "sppId" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "sppCreatedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "createdBy" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "updatedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "deletedBy" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`COMMENT ON COLUMN "short_urls"."hash" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_voucher_audit_logs"."metadata" IS NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ALTER COLUMN "status" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`CREATE INDEX "IDX_dbcc9fac7779f37be7791686c8" ON "tax_rules" ("accountCodePattern") `);
        await queryRunner.query(`CREATE INDEX "IDX_5dfb0aa9de7b0491c5a6f8b211" ON "tax_rules" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_823933c54c3030a05d47fa5afb" ON "tax_rules" ("effectiveFrom") `);
        await queryRunner.query(`CREATE INDEX "IDX_db681b51017ba5bd0294590b22" ON "spp" ("buktiBayarId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1b6ec36af5568f03d629fad62" ON "short_urls" ("hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_9e943f050c119ff3281c1f58aa" ON "short_urls" ("targetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a9dff8b38693df821a0b07b28" ON "short_urls" ("targetType") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac91f17eb687f4a80e3ab324cb" ON "short_urls" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_9388741ef4247614c11b6d2d83" ON "payment_voucher_attachments" ("voucherId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a25db6db900020e5c2b86b922a" ON "payment_voucher_attachments" ("attachmentType") `);
        await queryRunner.query(`CREATE INDEX "IDX_71e196a1ac4ca22df51ceb0d90" ON "payment_voucher_audit_logs" ("voucherId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c303bd5330cda36aa33c124ae4" ON "payment_voucher_audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_e00971c7eecb34b875e4a1d364" ON "payment_voucher_audit_logs" ("performedBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_3efb937b6c3290bbecd0a854aa" ON "payment_voucher_audit_logs" ("performedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_00ab11781bc2d1e83625b78c82" ON "payment_vouchers" ("voucherNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_fd2fc1bc1ea6eb71b8901b9856" ON "payment_vouchers" ("fiscalYear") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0507f41ac75f2729eedab573b" ON "payment_vouchers" ("voucherMonth") `);
        await queryRunner.query(`CREATE INDEX "IDX_a3a7917646e86b0c974a96df4d" ON "payment_vouchers" ("voucherDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_d82cbb0ba9bd93c0d28d0812f8" ON "payment_vouchers" ("kegiatanId") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc2464e91c23fa8f4a59e69991" ON "payment_vouchers" ("subKegiatanId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2c43aa3073cb32f4bdd1d3fc0" ON "payment_vouchers" ("accountCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_f6f209b306e04becfea0b9026b" ON "payment_vouchers" ("pptkId") `);
        await queryRunner.query(`CREATE INDEX "IDX_604e6d28c6d7fd8b6d52a514d1" ON "payment_vouchers" ("vendorName") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ea706969f16a0a3e94ea5e5d2" ON "payment_vouchers" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_df83bb7a70c4e27154e133a74e" ON "payment_vouchers" ("deletedAt") `);
        await queryRunner.query(`ALTER TABLE "bukti_bayar" ADD CONSTRAINT "FK_d6e99eb250ce00c6734bbfc5f9b" FOREIGN KEY ("anggaranKasId") REFERENCES "rencana_anggaran_kas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spp" ADD CONSTRAINT "FK_db681b51017ba5bd0294590b22d" FOREIGN KEY ("buktiBayarId") REFERENCES "bukti_bayar"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD CONSTRAINT "FK_9388741ef4247614c11b6d2d838" FOREIGN KEY ("voucherId") REFERENCES "payment_vouchers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD CONSTRAINT "FK_71e196a1ac4ca22df51ceb0d90e" FOREIGN KEY ("voucherId") REFERENCES "payment_vouchers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD CONSTRAINT "FK_5ae8f2b3420e8dce3f8a4dbf996" FOREIGN KEY ("taxRuleId") REFERENCES "tax_rules"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD CONSTRAINT "FK_cda876cca311a4a93c6011314ca" FOREIGN KEY ("sppId") REFERENCES "spp"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP CONSTRAINT "FK_cda876cca311a4a93c6011314ca"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP CONSTRAINT "FK_5ae8f2b3420e8dce3f8a4dbf996"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP CONSTRAINT "FK_71e196a1ac4ca22df51ceb0d90e"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP CONSTRAINT "FK_9388741ef4247614c11b6d2d838"`);
        await queryRunner.query(`ALTER TABLE "spp" DROP CONSTRAINT "FK_db681b51017ba5bd0294590b22d"`);
        await queryRunner.query(`ALTER TABLE "bukti_bayar" DROP CONSTRAINT "FK_d6e99eb250ce00c6734bbfc5f9b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df83bb7a70c4e27154e133a74e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ea706969f16a0a3e94ea5e5d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_604e6d28c6d7fd8b6d52a514d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6f209b306e04becfea0b9026b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2c43aa3073cb32f4bdd1d3fc0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc2464e91c23fa8f4a59e69991"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d82cbb0ba9bd93c0d28d0812f8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a3a7917646e86b0c974a96df4d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0507f41ac75f2729eedab573b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd2fc1bc1ea6eb71b8901b9856"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00ab11781bc2d1e83625b78c82"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3efb937b6c3290bbecd0a854aa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e00971c7eecb34b875e4a1d364"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c303bd5330cda36aa33c124ae4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71e196a1ac4ca22df51ceb0d90"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a25db6db900020e5c2b86b922a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9388741ef4247614c11b6d2d83"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac91f17eb687f4a80e3ab324cb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a9dff8b38693df821a0b07b28"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e943f050c119ff3281c1f58aa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1b6ec36af5568f03d629fad62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db681b51017ba5bd0294590b22"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_823933c54c3030a05d47fa5afb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5dfb0aa9de7b0491c5a6f8b211"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dbcc9fac7779f37be7791686c8"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "payment_voucher_audit_logs"."metadata" IS 'Metadata JSONB untuk informasi tambahan seperti IP, browser, device, field changes, dll'`);
        await queryRunner.query(`COMMENT ON COLUMN "short_urls"."hash" IS 'Short hash (8-16 karakter) yang di-embed di QR Code untuk verifikasi dokumen'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "deletedBy"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "updatedBy"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "sppCreatedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "sppId"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "rejectedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "rejectionBy"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "rejectionReason"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "approverSignedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "approverNip"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "approverName"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "approverId"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "treasurerNotes"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "treasurerSignedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "treasurerNip"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "treasurerName"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "treasurerId"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "receiverSignedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "receiverNip"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "receiverName"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "receiverId"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "technicalNotes"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "technicalSignedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "technicalOfficerNip"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "technicalOfficerName"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "technicalOfficerId"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "grossAmountText"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "netPayment"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "totalDeductions"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "skUmkmExpiry"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "skUmkmNumber"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pbjtAmount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pbjtRate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "includesPbjt"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "otherDeductionsNote"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "otherDeductions"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "ppnAmount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "ppnRate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph24Amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph24Rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pphFinalUmkmAmount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pphFinalUmkmRate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph4a2Amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph4a2Rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph23Amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph23Rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph22Amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph22Rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph21Amount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pph21Rate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "taxRuleId"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "grossAmount"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "invoiceDate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "invoiceNumbers"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "vendorAddress"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "vendorNpwp"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "vendorName"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "paymentPurpose"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "payeeName"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "pptkId"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "previousCommitments"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "rakMonthlyLimit"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "availablePagu"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "accountName"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "accountCode"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "subKegiatanName"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "subKegiatanCode"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "subKegiatanId"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "kegiatanName"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "kegiatanCode"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "kegiatanId"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "programName"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "programCode"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "programId"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "unitCode"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "voucherDate"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "voucherMonth"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "fiscalYear"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "voucherSequence"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP CONSTRAINT "UQ_00ab11781bc2d1e83625b78c820"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" DROP COLUMN "voucherNumber"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP COLUMN "performedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP COLUMN "performedBy"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP COLUMN "newStatus"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP COLUMN "oldStatus"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" DROP COLUMN "voucherId"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "uploadedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "uploadedBy"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "attachmentType"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "filePath"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "fileSize"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "fileType"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "fileName"`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" DROP COLUMN "voucherId"`);
        await queryRunner.query(`ALTER TABLE "short_urls" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "short_urls" DROP COLUMN "expiresAt"`);
        await queryRunner.query(`ALTER TABLE "short_urls" DROP COLUMN "targetType"`);
        await queryRunner.query(`ALTER TABLE "short_urls" DROP COLUMN "targetId"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "createdBy"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "effectiveTo"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "effectiveFrom"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "isFinalTax"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pbjtRate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "includesPbjt"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pph24Rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pphFinalUmkmRate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pph4a2Rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pph23Rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pph22Rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "pph21Rate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "ppnRate"`);
        await queryRunner.query(`ALTER TABLE "tax_rules" DROP COLUMN "accountCodePattern"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "approver_nip" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "approver_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "treasurer_notes" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "treasurer_nip" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "treasurer_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "receiver_nip" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "receiver_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "technical_notes" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "technical_officer_nip" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "technical_officer_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "gross_amount_text" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "sk_umkm_number" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "other_deductions_note" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "invoice_numbers" text array`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "vendor_address" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "vendor_npwp" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "vendor_name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "account_name" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "account_code" character varying(60)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "sub_kegiatan_name" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "sub_kegiatan_code" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "kegiatan_name" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "kegiatan_code" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "program_name" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "program_code" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "unit_code" character varying(20) NOT NULL DEFAULT 'RSUD-DS'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "created_by" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "rejection_reason" text`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "payee_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "payment_purpose" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "voucher_number" character varying(120) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD CONSTRAINT "UQ_52e465f91e3cf7db58200dfc7cd" UNIQUE ("voucher_number")`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "deleted_by" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "updated_by" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "spp_created_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "spp_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "approver_signed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "approver_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "treasurer_signed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "treasurer_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "receiver_signed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "receiver_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "technical_signed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "technical_officer_id" uuid`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["sikancil_dev","public","payment_vouchers","GENERATED_COLUMN","net_payment",""]);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "net_payment" numeric(15,2)`);
        await queryRunner.query(`INSERT INTO "typeorm_metadata"("database", "schema", "table", "type", "name", "value") VALUES ($1, $2, $3, $4, $5, $6)`, ["sikancil_dev","public","payment_vouchers","GENERATED_COLUMN","total_deductions",""]);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "total_deductions" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "sk_umkm_expiry" date`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pbjt_amount" numeric(15,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pbjt_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "includes_pbjt" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "other_deductions" numeric(15,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "ppn_amount" numeric(15,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "ppn_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph24_amount" numeric(15,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph24_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph_final_umkm_amount" numeric(15,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph_final_umkm_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph4a2_amount" numeric(15,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph4a2_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph23_amount" numeric(15,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph23_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph22_amount" numeric(15,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph22_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph21_amount" numeric(15,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pph21_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "tax_rule_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "invoice_date" date`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "pptk_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "previous_commitments" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "rak_monthly_limit" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "available_pagu" numeric(15,2)`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "sub_kegiatan_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "kegiatan_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "program_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "voucher_sequence" integer`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "rejected_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "rejection_by" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "gross_amount" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "rak_id_legacy" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "voucher_month" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "fiscal_year" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD "voucher_date" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD "new_status" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD "old_status" character varying(30)`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD "performed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD "voucher_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD "performed_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "attachment_type" character varying(30) NOT NULL DEFAULT 'OTHER'`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "file_path" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "file_type" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "file_name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "uploaded_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "uploaded_by" uuid`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "file_size" integer`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD "voucher_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "short_urls" ADD "target_type" character varying(50) NOT NULL DEFAULT 'PAYMENT_VOUCHER'`);
        await queryRunner.query(`ALTER TABLE "short_urls" ADD "created_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "short_urls" ADD "expires_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "short_urls" ADD "target_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "account_code_pattern" character varying(60) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "updated_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "created_at" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "created_by" uuid`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "effective_to" date`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "effective_from" date NOT NULL DEFAULT CURRENT_DATE`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "is_active" boolean DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "is_final_tax" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pbjt_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "includes_pbjt" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pph24_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pph_final_umkm_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pph4a2_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pph23_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pph22_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "pph21_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "tax_rules" ADD "ppn_rate" numeric(5,2) DEFAULT '0'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b14c90323ff9527cf9c4d2dbe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9fd380654c45b0b207ec89b85d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6e99eb250ce00c6734bbfc5f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_249b705de6a6a36f61236f17e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9be2dca70f1c1dd5b0aabc484b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_79c0ae56db7c4d1c9cc8d52383"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52e465f91e3cf7db58200dfc7c"`);
        await queryRunner.query(`DROP TABLE "bukti_bayar"`);
        await queryRunner.query(`COMMENT ON TABLE "payment_voucher_audit_logs" IS 'Audit trail lengkap untuk semua aktivitas payment voucher - untuk compliance dan tracking'`);
        await queryRunner.query(`COMMENT ON TABLE "payment_voucher_attachments" IS 'Tabel lampiran dokumen pendukung untuk payment voucher (invoice, kontrak, BA, BAST, foto, dll)'`);
        await queryRunner.query(`COMMENT ON TABLE "short_urls" IS 'Short URL untuk QR Code verification - setiap payment voucher mendapat hash unik untuk verifikasi keaslian'`);
        await queryRunner.query(`ALTER TABLE "spp" RENAME COLUMN "buktiBayarId" TO "payment_voucher_id"`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD CONSTRAINT "chk_spp_only_when_approved" CHECK (((spp_id IS NULL) OR ((status)::text = ANY ((ARRAY['APPROVED'::character varying, 'SPP_CREATED'::character varying])::text[]))))`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD CONSTRAINT "chk_deductions_not_exceed_gross" CHECK ((total_deductions <= gross_amount))`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD CONSTRAINT "chk_net_payment_positive" CHECK ((net_payment >= (0)::numeric))`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD CONSTRAINT "chk_gross_amount_positive" CHECK ((gross_amount > (0)::numeric))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_pv_sequence_unique" ON "payment_vouchers" ("account_code", "fiscal_year", "unit_code", "voucher_month", "voucher_sequence") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_pv_not_deleted" ON "payment_vouchers" ("deleted_at") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_pv_voucher_date" ON "payment_vouchers" ("voucher_date") `);
        await queryRunner.query(`CREATE INDEX "idx_pv_vendor" ON "payment_vouchers" ("vendor_name") `);
        await queryRunner.query(`CREATE INDEX "idx_pv_status" ON "payment_vouchers" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_pv_pptk" ON "payment_vouchers" ("pptk_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pv_sub_kegiatan" ON "payment_vouchers" ("sub_kegiatan_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pv_kegiatan" ON "payment_vouchers" ("kegiatan_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pv_account_code" ON "payment_vouchers" ("account_code") `);
        await queryRunner.query(`CREATE INDEX "idx_pv_year_month" ON "payment_vouchers" ("fiscal_year", "voucher_month") `);
        await queryRunner.query(`CREATE INDEX "idx_pv_fiscal_year" ON "payment_vouchers" ("fiscal_year") `);
        await queryRunner.query(`CREATE INDEX "idx_pv_voucher_number" ON "payment_vouchers" ("voucher_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b14c90323ff9527cf9c4d2dbe" ON "payment_vouchers" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_79c0ae56db7c4d1c9cc8d52383" ON "payment_vouchers" ("voucher_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_52e465f91e3cf7db58200dfc7c" ON "payment_vouchers" ("voucher_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6e99eb250ce00c6734bbfc5f9" ON "payment_vouchers" ("rak_id_legacy") `);
        await queryRunner.query(`CREATE INDEX "IDX_249b705de6a6a36f61236f17e9" ON "payment_vouchers" ("voucher_month") `);
        await queryRunner.query(`CREATE INDEX "IDX_9be2dca70f1c1dd5b0aabc484b" ON "payment_vouchers" ("fiscal_year") `);
        await queryRunner.query(`CREATE INDEX "idx_pval_metadata" ON "payment_voucher_audit_logs" ("metadata") `);
        await queryRunner.query(`CREATE INDEX "idx_pval_performed_by" ON "payment_voucher_audit_logs" ("performed_by") `);
        await queryRunner.query(`CREATE INDEX "idx_pval_action" ON "payment_voucher_audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "idx_pval_performed" ON "payment_voucher_audit_logs" ("performed_at") `);
        await queryRunner.query(`CREATE INDEX "idx_pval_voucher" ON "payment_voucher_audit_logs" ("voucher_id") `);
        await queryRunner.query(`CREATE INDEX "idx_pva_type" ON "payment_voucher_attachments" ("attachment_type") `);
        await queryRunner.query(`CREATE INDEX "idx_pva_voucher" ON "payment_voucher_attachments" ("voucher_id") `);
        await queryRunner.query(`CREATE INDEX "idx_short_urls_expires" ON "short_urls" ("expires_at") WHERE (expires_at IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_short_urls_target" ON "short_urls" ("target_id", "target_type") `);
        await queryRunner.query(`CREATE INDEX "idx_short_urls_hash" ON "short_urls" ("hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_db681b51017ba5bd0294590b22" ON "spp" ("payment_voucher_id") `);
        await queryRunner.query(`CREATE INDEX "idx_tax_rules_active" ON "tax_rules" ("effective_from", "is_active") `);
        await queryRunner.query(`CREATE INDEX "idx_tax_rules_pattern" ON "tax_rules" ("account_code_pattern") `);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD CONSTRAINT "FK_pv_spp" FOREIGN KEY ("spp_id") REFERENCES "spp"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD CONSTRAINT "FK_pv_tax_rule" FOREIGN KEY ("tax_rule_id") REFERENCES "tax_rules"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_vouchers" ADD CONSTRAINT "FK_d6e99eb250ce00c6734bbfc5f9b" FOREIGN KEY ("rak_id_legacy") REFERENCES "rencana_anggaran_kas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD CONSTRAINT "FK_pval_user" FOREIGN KEY ("performed_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_audit_logs" ADD CONSTRAINT "FK_pval_voucher" FOREIGN KEY ("voucher_id") REFERENCES "payment_vouchers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_voucher_attachments" ADD CONSTRAINT "FK_pva_voucher" FOREIGN KEY ("voucher_id") REFERENCES "payment_vouchers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spp" ADD CONSTRAINT "FK_spp_payment_voucher" FOREIGN KEY ("payment_voucher_id") REFERENCES "payment_vouchers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spp" ADD CONSTRAINT "FK_db681b51017ba5bd0294590b22d" FOREIGN KEY ("payment_voucher_id") REFERENCES "payment_vouchers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
