import { AppDataSource } from '../data-source';
import { ChartOfAccount } from '../entities/chart-of-account.entity';
import { AccountType } from '../enums';

/**
 * Chart of Accounts Seeder
 * Seeds COA structure (5 levels) compliant with BLUD accounting
 */
export async function seedChartOfAccounts() {
  const coaRepository = AppDataSource.getRepository(ChartOfAccount);

  const accounts: Partial<ChartOfAccount>[] = [
    // ===== ASET (1.x.x.x.x) =====
    {
      kodeRekening: '1',
      namaRekening: 'ASET',
      jenisAkun: AccountType.ASSET,
      level: 1,
      isHeader: true,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    // ASET LANCAR (1.1.x.x.x)
    {
      kodeRekening: '1.1',
      namaRekening: 'ASET LANCAR',
      jenisAkun: AccountType.ASSET,
      level: 2,
      parentKode: '1',
      isHeader: true,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '1.1.1',
      namaRekening: 'Kas dan Setara Kas',
      jenisAkun: AccountType.ASSET,
      level: 3,
      parentKode: '1.1',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '1.1.1.01',
      namaRekening: 'Kas',
      jenisAkun: AccountType.ASSET,
      level: 4,
      parentKode: '1.1.1',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '1.1.1.02',
      namaRekening: 'Bank - Rekening Utama',
      jenisAkun: AccountType.ASSET,
      level: 4,
      parentKode: '1.1.1',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '1.1.1.03',
      namaRekening: 'Bank - Rekening Operasional',
      jenisAkun: AccountType.ASSET,
      level: 4,
      parentKode: '1.1.1',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '1.1.2',
      namaRekening: 'Piutang',
      jenisAkun: AccountType.ASSET,
      level: 3,
      parentKode: '1.1',
      isHeader: true,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '1.1.2.01',
      namaRekening: 'Piutang Usaha',
      jenisAkun: AccountType.ASSET,
      level: 4,
      parentKode: '1.1.2',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '1.1.2.02',
      namaRekening: 'Piutang Lain-lain',
      jenisAkun: AccountType.ASSET,
      level: 4,
      parentKode: '1.1.2',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },

    // ASET TETAP (1.2.x.x.x)
    {
      kodeRekening: '1.2',
      namaRekening: 'ASET TETAP',
      jenisAkun: AccountType.ASSET,
      level: 2,
      parentKode: '1',
      isHeader: true,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '1.2.1',
      namaRekening: 'Tanah',
      jenisAkun: AccountType.ASSET,
      level: 3,
      parentKode: '1.2',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '1.2.2',
      namaRekening: 'Bangunan',
      jenisAkun: AccountType.ASSET,
      level: 3,
      parentKode: '1.2',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '1.2.3',
      namaRekening: 'Peralatan Medis',
      jenisAkun: AccountType.ASSET,
      level: 3,
      parentKode: '1.2',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '1.2.4',
      namaRekening: 'Kendaraan',
      jenisAkun: AccountType.ASSET,
      level: 3,
      parentKode: '1.2',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '1.2.5',
      namaRekening: 'Akumulasi Penyusutan',
      jenisAkun: AccountType.ASSET,
      level: 3,
      parentKode: '1.2',
      isHeader: false,
      normalBalance: 'CREDIT',
      isBudgetControl: false,
    },

    // ===== KEWAJIBAN (2.x.x.x.x) =====
    {
      kodeRekening: '2',
      namaRekening: 'KEWAJIBAN',
      jenisAkun: AccountType.LIABILITY,
      level: 1,
      isHeader: true,
      normalBalance: 'CREDIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '2.1',
      namaRekening: 'KEWAJIBAN JANGKA PENDEK',
      jenisAkun: AccountType.LIABILITY,
      level: 2,
      parentKode: '2',
      isHeader: true,
      normalBalance: 'CREDIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '2.1.1',
      namaRekening: 'Hutang Usaha',
      jenisAkun: AccountType.LIABILITY,
      level: 3,
      parentKode: '2.1',
      isHeader: false,
      normalBalance: 'CREDIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '2.1.2',
      namaRekening: 'Hutang Pajak',
      jenisAkun: AccountType.LIABILITY,
      level: 3,
      parentKode: '2.1',
      isHeader: true,
      normalBalance: 'CREDIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '2.1.2.01',
      namaRekening: 'Hutang PPh 21',
      jenisAkun: AccountType.LIABILITY,
      level: 4,
      parentKode: '2.1.2',
      isHeader: false,
      normalBalance: 'CREDIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '2.1.2.02',
      namaRekening: 'Hutang PPh 23',
      jenisAkun: AccountType.LIABILITY,
      level: 4,
      parentKode: '2.1.2',
      isHeader: false,
      normalBalance: 'CREDIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '2.1.2.03',
      namaRekening: 'Hutang PPN',
      jenisAkun: AccountType.LIABILITY,
      level: 4,
      parentKode: '2.1.2',
      isHeader: false,
      normalBalance: 'CREDIT',
      isBudgetControl: false,
    },

    // ===== EKUITAS (3.x.x.x.x) =====
    {
      kodeRekening: '3',
      namaRekening: 'EKUITAS',
      jenisAkun: AccountType.EQUITY,
      level: 1,
      isHeader: true,
      normalBalance: 'CREDIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '3.1',
      namaRekening: 'Ekuitas Awal',
      jenisAkun: AccountType.EQUITY,
      level: 2,
      parentKode: '3',
      isHeader: false,
      normalBalance: 'CREDIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '3.2',
      namaRekening: 'Surplus (Defisit) Tahun Berjalan',
      jenisAkun: AccountType.EQUITY,
      level: 2,
      parentKode: '3',
      isHeader: false,
      normalBalance: 'CREDIT',
      isBudgetControl: false,
    },

    // ===== PENDAPATAN (4.x.x.x.x) =====
    {
      kodeRekening: '4',
      namaRekening: 'PENDAPATAN',
      jenisAkun: AccountType.REVENUE,
      level: 1,
      isHeader: true,
      normalBalance: 'CREDIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '4.1',
      namaRekening: 'PENDAPATAN BLUD',
      jenisAkun: AccountType.REVENUE,
      level: 2,
      parentKode: '4',
      isHeader: true,
      normalBalance: 'CREDIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '4.1.1',
      namaRekening: 'Pendapatan APBD',
      jenisAkun: AccountType.REVENUE,
      level: 3,
      parentKode: '4.1',
      isHeader: false,
      normalBalance: 'CREDIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '4.1.2',
      namaRekening: 'Pendapatan Fungsional',
      jenisAkun: AccountType.REVENUE,
      level: 3,
      parentKode: '4.1',
      isHeader: true,
      normalBalance: 'CREDIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '4.1.2.01',
      namaRekening: 'Pendapatan Layanan Rawat Jalan',
      jenisAkun: AccountType.REVENUE,
      level: 4,
      parentKode: '4.1.2',
      isHeader: false,
      normalBalance: 'CREDIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '4.1.2.02',
      namaRekening: 'Pendapatan Layanan Rawat Inap',
      jenisAkun: AccountType.REVENUE,
      level: 4,
      parentKode: '4.1.2',
      isHeader: false,
      normalBalance: 'CREDIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '4.1.3',
      namaRekening: 'Pendapatan Hibah',
      jenisAkun: AccountType.REVENUE,
      level: 3,
      parentKode: '4.1',
      isHeader: false,
      normalBalance: 'CREDIT',
      isBudgetControl: true,
    },

    // ===== BEBAN (5.x.x.x.x) =====
    {
      kodeRekening: '5',
      namaRekening: 'BEBAN',
      jenisAkun: AccountType.EXPENSE,
      level: 1,
      isHeader: true,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '5.1',
      namaRekening: 'BEBAN PEGAWAI',
      jenisAkun: AccountType.EXPENSE,
      level: 2,
      parentKode: '5',
      isHeader: true,
      normalBalance: 'DEBIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '5.1.1',
      namaRekening: 'Gaji Pokok',
      jenisAkun: AccountType.EXPENSE,
      level: 3,
      parentKode: '5.1',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '5.1.2',
      namaRekening: 'Tunjangan',
      jenisAkun: AccountType.EXPENSE,
      level: 3,
      parentKode: '5.1',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '5.2',
      namaRekening: 'BEBAN BARANG DAN JASA',
      jenisAkun: AccountType.EXPENSE,
      level: 2,
      parentKode: '5',
      isHeader: true,
      normalBalance: 'DEBIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '5.2.1',
      namaRekening: 'Beban Obat dan Bahan Medis',
      jenisAkun: AccountType.EXPENSE,
      level: 3,
      parentKode: '5.2',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '5.2.2',
      namaRekening: 'Beban Alat Tulis Kantor',
      jenisAkun: AccountType.EXPENSE,
      level: 3,
      parentKode: '5.2',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '5.2.3',
      namaRekening: 'Beban Listrik dan Air',
      jenisAkun: AccountType.EXPENSE,
      level: 3,
      parentKode: '5.2',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '5.3',
      namaRekening: 'BEBAN MODAL',
      jenisAkun: AccountType.EXPENSE,
      level: 2,
      parentKode: '5',
      isHeader: true,
      normalBalance: 'DEBIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '5.3.1',
      namaRekening: 'Beban Perolehan Peralatan Medis',
      jenisAkun: AccountType.EXPENSE,
      level: 3,
      parentKode: '5.3',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '5.3.2',
      namaRekening: 'Beban Perolehan Kendaraan',
      jenisAkun: AccountType.EXPENSE,
      level: 3,
      parentKode: '5.3',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: true,
    },
    {
      kodeRekening: '5.4',
      namaRekening: 'BEBAN LAIN-LAIN',
      jenisAkun: AccountType.EXPENSE,
      level: 2,
      parentKode: '5',
      isHeader: true,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
    {
      kodeRekening: '5.4.1',
      namaRekening: 'Beban Penyusutan',
      jenisAkun: AccountType.EXPENSE,
      level: 3,
      parentKode: '5.4',
      isHeader: false,
      normalBalance: 'DEBIT',
      isBudgetControl: false,
    },
  ];

  console.log(`📋 Seeding ${accounts.length} chart of accounts...`);

  for (const accountData of accounts) {
    const existing = await coaRepository.findOne({
      where: { kodeRekening: accountData.kodeRekening },
    });

    if (!existing) {
      const account = coaRepository.create(accountData);
      await coaRepository.save(account);
      console.log(`   ✅ ${accountData.kodeRekening} - ${accountData.namaRekening}`);
    } else {
      console.log(`   ⏭️  ${accountData.kodeRekening} - Already exists`);
    }
  }

  console.log('✅ Chart of Accounts seeded successfully');
}
