/**
 * Enum: JenisRevisiRBA
 * Jenis revisi RBA
 */
export enum JenisRevisiRBA {
  PERUBAHAN_PAGU = 'PERUBAHAN_PAGU',
  PERUBAHAN_VOLUME = 'PERUBAHAN_VOLUME',
  PERUBAHAN_WAKTU = 'PERUBAHAN_WAKTU',
  PERGESERAN_ANGGARAN = 'PERGESERAN_ANGGARAN',
  LAIN_LAIN = 'LAIN_LAIN',
}
