export enum VoucherAuditAction {
  CREATED = 'CREATED',
  UPDATED = 'UPDATED',
  SUBMITTED = 'SUBMITTED',
  APPROVED_TECHNICAL = 'APPROVED_TECHNICAL',
  APPROVED_TREASURER = 'APPROVED_TREASURER',
  APPROVED_FINAL = 'APPROVED_FINAL',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  SPP_CREATED = 'SPP_CREATED',
  PRINTED = 'PRINTED',
  DELETED = 'DELETED',
  RESTORED = 'RESTORED',
}
